### ISSUE TITLE
C9H5N43O8P3S2

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#3]
Hi,

I ran 

```
PFG test -m 1000 -t 50000  --C 8-10 --H 4-6 --N 42-44 --O 7-9 --S 1-3 --P 2-4 -r
```

This should find the formula C9H5N43O8P3S2 (mass 999.996059 Da),  but it does not report any formulas. Is that a bug?

**Comment by zmzhang** [comment]
Hi Tomas:

Thanks for the feedback!
PFG can't find this formula because of its number of N is too large.
We have constraints on largest number of elements with knowledge from databases such as NIST, Wiley and DNP.

Now these  constraints have been removed. Please see [commit a9a3bec ](https://github.com/zmzhang/PFG/commit/a9a3bec628030de6e4221684451d2e9ec8e3cd7a) for more details.

PFG can find C9H5N43O8P3S2 efficiently.
![max_constrains](https://cloud.githubusercontent.com/assets/6937141/17428959/94ff3912-5b1e-11e6-8b20-0407f3cae487.png)

Cheers!
Zhimin

**Comment by tomas-pluskal** [comment]
I think the constraints on the element counts could be added as an optional rule.
