### ISSUE TITLE
1000000 results limit

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#5]
Hi Zhimin,

Thanks for quickly fixing the issues I reported. I found one more: the number of results is currently limited to 1,000,000 due to the fixed size of [this array](https://github.com/zmzhang/PFG/blob/master/formula.cpp#L166). With larger masses, we can easily hit this limit.

Would it be possible to adjust the array size dynamically?

In fact, I think the best solution would be to avoid using the array completely (think of memory usage) and print the formulas to the output file as they are generated (it would require some thread synchronization of course)

Tomas

**Comment by zmzhang** [comment]
Hi Tomas:

Thanks for your suggestion.

File IO is time-consuming. If write result for each generated formula, most of the CPU time will wait for the finish of file IO unless asynchronous IO is used.

In order to solve this problem, a abstract layer has been added to provide the function of pooled IO for the generating results. The details are:
 A class named ResultsWriter has been added in [formula.h](https://github.com/zmzhang/PFG/blob/e7f294caf87f07bb6aa36fffbfbe65560142a4e1/formula.h#L48). It will allocate m_poolSize of results to storage the generated formula. If the pool is full, ResultsWriter can write the results to file and reset the pool. 

![pool](https://cloud.githubusercontent.com/assets/6937141/17453473/d3656a42-5bae-11e6-947a-1b908c4c4ce0.png)

Regards
Zhimin

**Comment by tomas-pluskal** [comment]
Thanks, that's a nice solution.

**Comment by tomas-pluskal** [comment]
Hi Zhimin,

Even after the recent changes, the number of PFG results is limited to 1000000.
I think it is because every time writeResults() is called, you overwrite the result file with a new one (https://github.com/zmzhang/PFG/blob/master/formula.cpp#L218).

Perhaps the fopen call should be moved to the ResultsWriter constructor.
Also, the [header](https://github.com/zmzhang/PFG/blob/master/formula.cpp#L229) should be written only once.

**Comment by zmzhang** [comment]
Hi Tomas:

You are right.
The fopen and fclose have been moved to constructor and destructor of ResultsWriter respectivly.
The header has also moved to constructor of ResultsWriter, and it will write only once.

Please see [commit 2ebef02](https://github.com/zmzhang/PFG/commit/2ebef02724344bd7df372a6c3c52e079e841a87b).

Thanks!
Zhimin
