### ISSUE TITLE
segfault with 12 elements

### ISSUE THREAD

**Issue by tomas-pluskal** [zmzhang/PFG#8]
Command tested:

```
PFG test -m 100 -u Da -t 0.001 --C 0-100 --H 0-100 --N 0-100 --O 0-100 --S 0-100 --P 0-100 --D 0-100 --F 0-100 --Na 0-100 --Si 0-100 --Cl 0-100 --Br 0-100
```

Result:

```
formula  mass    mz  error   rdbe
*** glibc detected *** PFG/PFG: free(): invalid next size (fast): 0x00007f2c100008c0 ***
Aborted (core dumped)
```

**Comment by zmzhang** [comment]
Hi Tomas:

It is a mistake in our code.
We allocate a fixed size (10) current array for storage elements, numbers.
It will cause  segfault with elements larger than 10.
Now it has been fixed by changing the array size to the given element number.

Please see [commit 158f850 ](https://github.com/zmzhang/PFG/commit/158f850358d500f0150425fd65da39bfbe3d1396).

The [release file](https://github.com/zmzhang/PFG/releases/download/1.1/PFG.1.1_x86.zip) is updated too.

![12](https://cloud.githubusercontent.com/assets/6937141/17460129/b5fdf10e-5c8a-11e6-92a8-6e337eaa60a9.png)

Regards
Zhimin
